[package]
name = "one_for_all"
version = "0.1.0"
edition = "2021"
# path to main.rs or lib.rs
src = "src/main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.10.1"
